---
title: "Untitled"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(osmdata)
library(dplyr)
library(plotly)
library(stringr)
library(sf)
library(ggmap)
library(tidyverse)
library(readr)
library(leaflet)

#saveRDS(df_ntp,file = "osmData_NewTaipei.rds")
readRDS("support/osmData_NewTaipei.rds")-> df_ntp
readRDS("support/confirmed.rds") -> confirmed
readRDS("support/osmData_NewTaipei_fullEN.rds")-> test
NTP_confirmed_data <- read_csv("support/0628NTP_confirmed_data.csv")

```

```{r}
case = colorspace::sequential_hcl(n=3, h =0 , c = c(200, 0), l = 30, rev = TRUE, power = 1.75)
grDevices::colorRamp(case) -> case_colorGenerator
```

```{r, 確診者待解除隔離面量圖}
plotly::plot_ly() %>%
  add_sf(
    data =  df_ntp$osm_multipolygons,
    type= "scatter",
    split= ~name.en,
    showlegend=F,
    hoverinfo="text",
    text= ~name_and_case_number,
    hoveron = "fills",
    stroke=I("gray"),
    color = ~Range, 
    colors = grDevices::colorRamp(case),
    hoverlabel = list(
      bgcolor="orange",
      font=list(
        color="black",
        size=15
      )
    )
  )
```

```{r, 確診者待解除w/Leaflet} 
greenLeafIcon <- makeIcon(
  iconUrl = "http://leafletjs.com/examples/custom-icons/leaf-green.png",
  iconWidth = 38, iconHeight = 95,
  iconAnchorX = 22, iconAnchorY = 94,
  shadowUrl = "http://leafletjs.com/examples/custom-icons/leaf-shadow.png",
  shadowWidth = 50, shadowHeight = 64,
  shadowAnchorX = 4, shadowAnchorY = 62
)

m <- leaflet(confirmed) %>% 
  setView(
  lng = 121.5454, lat=24.9928,zoom = 10.3
   ) %>% addTiles() %>% 
  addMarkers(
    lng = ~lon,
  lat = ~lat,
  icon = greenLeafIcon,
  clusterOptions = markerClusterOptions())

m
```

```{r}
readr::read_csv("support/regionCenter.csv") -> centerData
```

```{r, ggplot確診數量時間序列圖}
table(NTP_confirmed_data$發病日.從BO抓取.) -> day_confirmed
day_confirmed %>% as.data.frame() -> day_confirmed_dataFrame

day_confirmed_dataFrame %>% mutate(
   date =   day_confirmed_dataFrame$Var1,
   daycases = day_confirmed_dataFrame$Freq
) -> day_confirmed_dataFrame

day_confirmed_dataFrame %>% select(.,-c(Var1,Freq)) -> day_confirmed_dataFrame

day_confirmed_dataFrame$date %>% as.Date() -> day_confirmed_dataFrame$date

day_confirmed_dataFrame %>% 
  ggplot()+
  geom_col(
    data = day_confirmed_dataFrame,
    aes(x = date, y = daycases),
    
) 
```

```{r plotly新增病例時間序列圖}
NTP_confirmed_data$`發病日(從BO抓取)` %>% as.Date() -> NTP_confirmed_data$`發病日(從BO抓取)`
#saveRDS(NTP_confirmed_data,"NTP_confirmed_data.rds")

NTP_confirmed_data %>% filter(.,`有效地址` = TRUE) -> test

table(NTP_confirmed_data$`發病日(從BO抓取)`) %>% as.data.frame() -> test

table(test$發病日.從BO抓取.) %>% as.data.frame() -> table1

table1 %>% mutate(
  Var1 = as.Date(Var1)
) -> table1

plot_ly(
  data = NTP_confirmed_data,
  x = ~`發病日(從BO抓取)`,
  type = "histogram",
  stroke = I("white")
) %>% config(displayModeBar = F)

plot_ly(
  data = table1,
  x = ~`Var1`,
  y = ~Freq,
  type = "bar",
  stroke = I("white")
) %>% config(displayModeBar = F) 

plot_ly(
  data = table1,
  x = ~`Var1`,
  y = ~Freq,
  type = "scatter",
  mode = "line",
  stroke = I("white")
) 
```

```{r}
NTP_confirmed_data$TOWNNAME %>% table() -> confirmed_by_city
confirmed_by_city %>% as.data.frame() -> cumulative_city

cumulative_city$. <- factor(cumulative_city$., levels = unique(cumulative_city$.)[order(cumulative_city$Freq, decreasing = F)])

cumulative_city %>% plot_ly(
  x = ~.,
  y = ~Freq,
  type = "bar",
  marker = list(color = ~Freq,
                colors = grDevices::colorRamp(case) ,
                line = list(color = 'rgb(8,48,107)',
                                  width = 1.5))
) %>%
layout(
     title = list(text = "累積確診量(都市分類)，y為數量", y = 0.95),
     xaxis = list(title = ""),
     yaxis = list(title = ""),
     paper_bgcolor='#cfd8dc',
     plot_bgcolor='#cfd8dc'
) -> plotly_cumulative

plotly_cumulative
```
